// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Y1UblkUM7rTfr5vb899VyYL3v9Zbx4M',
    appId: '1:898418783424:web:83d8d5f7af65b93639a925',
    messagingSenderId: '898418783424',
    projectId: 'carloan-flutter-project',
    authDomain: 'carloan-flutter-project.firebaseapp.com',
    storageBucket: 'carloan-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlxirFeqWknJzbeRRVeNrXdhOlvILrsoc',
    appId: '1:898418783424:android:8f7fe1bbccbcfdf939a925',
    messagingSenderId: '898418783424',
    projectId: 'carloan-flutter-project',
    storageBucket: 'carloan-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3PVC1pFVFYZ-JsDxGRhJfppvBJ7dhsk8',
    appId: '1:898418783424:ios:24dde44988f1294939a925',
    messagingSenderId: '898418783424',
    projectId: 'carloan-flutter-project',
    storageBucket: 'carloan-flutter-project.appspot.com',
    iosClientId: '898418783424-g3s1g4h757io2n1q2pq7kuicr4qb3v5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.carLoanProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3PVC1pFVFYZ-JsDxGRhJfppvBJ7dhsk8',
    appId: '1:898418783424:ios:24dde44988f1294939a925',
    messagingSenderId: '898418783424',
    projectId: 'carloan-flutter-project',
    storageBucket: 'carloan-flutter-project.appspot.com',
    iosClientId: '898418783424-g3s1g4h757io2n1q2pq7kuicr4qb3v5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.carLoanProject',
  );
}
